#!/usr/bin/env node

/**
 * v2.0 backend codegen. Reads the `dataModel` section of an app-spec IR and emits
 * a typed local backend under src/backend/generated/: a Drizzle schema (types +
 * column metadata only — no SQL engine runs in v2.0), drizzle-zod validators,
 * tRPC CRUD routers, a repos map over the on-device store, and typed hooks.
 *
 * The generator does ZERO inference — the /clone-app --backend=mock skill phase
 * produces the reviewed dataModel; this only templates it. Pure Node, no deps.
 *
 * Usage: node scripts/gen-backend.mjs [path/to/app-spec.json]
 *   default input: docs/research/app-spec.json
 */

import { readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SPEC_REL = process.argv[2] || 'docs/research/app-spec.json';
const OUT = 'src/backend/generated';

// ── Read + guard ────────────────────────────────────────────────────────────
let spec;
try {
  spec = JSON.parse(readFileSync(join(ROOT, SPEC_REL), 'utf8'));
} catch {
  console.error(`gen-backend: cannot read spec at ${SPEC_REL}`);
  process.exit(1);
}
const dm = spec.dataModel;
if (!dm || !Array.isArray(dm.entities) || dm.entities.length === 0) {
  console.log('gen-backend: no dataModel in the spec — nothing to generate.');
  console.log('  Run /clone-app --backend=mock first (it writes the dataModel), or pass a spec that has one.');
  process.exit(0);
}
const entities = dm.entities;

// ── Naming + type helpers ─────────────────────────────────────────────────────
const snake = (s) => s.replace(/[A-Z]/g, (m) => '_' + m.toLowerCase());
const cap = (s) => s.charAt(0).toUpperCase() + s.slice(1);
const camel = (s) => s.charAt(0).toLowerCase() + s.slice(1);
const enumUnion = (f) => f.enumValues.map((v) => `'${v}'`).join(' | ');

// A single field -> a drizzle-orm/sqlite-core column expression.
// v2.0 is JSON/AsyncStorage-backed, so timestamps are epoch-ms numbers (NOT
// Date-mode) to stay JSON-round-trippable. v2.1 re-emits these as pg-core.
function colExpr(f) {
  const col = snake(f.name);
  if (f.type === 'id') return `text('${col}').primaryKey()`;
  let base;
  switch (f.type) {
    case 'text': base = `text('${col}')`; break;
    case 'integer': base = `integer('${col}')`; break;
    case 'real': base = `real('${col}')`; break;
    case 'boolean': base = `integer('${col}', { mode: 'boolean' })`; break;
    case 'timestamp': base = `integer('${col}')`; break; // epoch ms; v2.1 -> timestamptz
    case 'enum': base = `text('${col}').$type<${enumUnion(f)}>()`; break;
    default: base = `text('${col}')`;
  }
  return f.optional ? base : base + '.notNull()';
}

// Which sqlite-core builders does the whole model use?
function sqliteImports() {
  const used = new Set(['sqliteTable']);
  for (const e of entities) {
    for (const f of e.fields) {
      if (f.type === 'id' || f.type === 'text' || f.type === 'enum') used.add('text');
      else if (f.type === 'integer' || f.type === 'boolean' || f.type === 'timestamp') used.add('integer');
      else if (f.type === 'real') used.add('real');
    }
    if (Array.isArray(e.relations) && e.relations.length) used.add('text');
  }
  // stable order
  return ['sqliteTable', 'text', 'integer', 'real'].filter((n) => used.has(n));
}

// ── Emit ──────────────────────────────────────────────────────────────────────
const manifest = [];
function write(rel, content) {
  const full = join(ROOT, rel);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content.replace(/\n{3,}/g, '\n\n'), 'utf8');
  manifest.push(rel);
  console.log(`  ✓ ${rel}`);
}
const H = `// AUTO-GENERATED by scripts/gen-backend.mjs from ${SPEC_REL} (dataModel).\n// Do not edit by hand. Re-run: node scripts/gen-backend.mjs\n`;

// wipe the generated tree so removed entities never leave stale files
rmSync(join(ROOT, OUT), { recursive: true, force: true });

console.log(`gen-backend: ${entities.length} entit${entities.length === 1 ? 'y' : 'ies'} from ${SPEC_REL}\n`);

// 1. schema.ts — Drizzle tables (types + column metadata only)
{
  let out = `${H}//\n// Drizzle is the TYPE + column source of truth. In v2.0 no SQL engine runs;\n// these tables provide \$inferSelect types and feed the drizzle-zod validators.\n// v2.1 re-emits the same model as pg-core against Supabase Postgres.\nimport { ${sqliteImports().join(', ')} } from 'drizzle-orm/sqlite-core';\n`;
  for (const e of entities) {
    out += `\nexport const ${e.table} = sqliteTable('${e.table}', {\n`;
    for (const f of e.fields) out += `  ${f.name}: ${colExpr(f)},\n`;
    for (const r of e.relations ?? []) {
      out += `  // @proposal FK hint (unverified — confirm): ${r.kind} ${r.references}.`;
      out += r.evidence ? ` Evidence: ${r.evidence}.` : '';
      out += `\n  // Emitted as a plain nullable column, never a database foreign key (screenshot FK recovery is unreliable).\n`;
      out += `  ${r.field}: text('${snake(r.field)}'),\n`;
    }
    out += `});\nexport type ${e.name} = typeof ${e.table}.\$inferSelect;\n`;
  }
  write(`${OUT}/schema.ts`, out);
}

// 2. validators.ts — drizzle-zod create/update schemas (zod v4, matching drizzle-zod 0.8)
{
  const anyEnum = entities.some((e) => e.fields.some((f) => f.type === 'enum'));
  let out = `${H}//\n// drizzle-zod validators drive the tRPC write path. zod is imported from 'zod/v4'\n// to match drizzle-zod 0.8 (which builds zod-4 schemas internally).\nimport { createSelectSchema } from 'drizzle-zod';\n`;
  if (anyEnum) out += `import { z } from 'zod/v4';\n`;
  out += `import { ${entities.map((e) => e.table).join(', ')} } from './schema';\n`;
  for (const e of entities) {
    const enums = e.fields.filter((f) => f.type === 'enum');
    const refine = enums.length
      ? `, { ${enums.map((f) => `${f.name}: z.enum([${f.enumValues.map((v) => `'${v}'`).join(', ')}])`).join(', ')} }`
      : '';
    const c = camel(e.name);
    out += `\nconst ${c}Row = createSelectSchema(${e.table}${refine});\n`;
    out += `export const ${c}Create = ${c}Row.omit({ id: true });\n`;
    out += `export const ${c}Update = ${c}Create.partial();\n`;
  }
  write(`${OUT}/validators.ts`, out);
}

// 3. seed.ts — rows lifted from each screen's Mock Data (typed to the entity)
{
  let out = `${H}//\n// Seed rows from the cloned app's Mock Data. Hydrate each table so the clone\n// is not empty. An entity with no sampleRows seeds to [].\nimport type { ${entities.map((e) => e.name).join(', ')} } from './schema';\n`;
  for (const e of entities) {
    const rows = Array.isArray(e.sampleRows) ? e.sampleRows : [];
    out += `\nexport const ${camel(e.name)}Seed: ${e.name}[] = ${JSON.stringify(rows, null, 2)};\n`;
  }
  write(`${OUT}/seed.ts`, out);
}

// 4. routers/<entity>.ts — one tRPC CRUD router per entity
for (const e of entities) {
  const c = camel(e.name);
  const out =
    `${H}import { z } from 'zod/v4';\n` +
    `import { publicProcedure, router } from '../../trpc/init';\n` +
    `import { ${c}Create, ${c}Update } from '../validators';\n\n` +
    `export const ${c}Router = router({\n` +
    `  list: publicProcedure.query(({ ctx }) => ctx.repos.${e.table}.list()),\n` +
    `  get: publicProcedure.input(z.object({ id: z.string() })).query(({ ctx, input }) => ctx.repos.${e.table}.get(input.id)),\n` +
    `  create: publicProcedure.input(${c}Create).mutation(({ ctx, input }) => ctx.repos.${e.table}.create(input)),\n` +
    `  update: publicProcedure\n    .input(z.object({ id: z.string(), patch: ${c}Update }))\n    .mutation(({ ctx, input }) => ctx.repos.${e.table}.update(input.id, input.patch)),\n` +
    `  remove: publicProcedure.input(z.object({ id: z.string() })).mutation(({ ctx, input }) => ctx.repos.${e.table}.remove(input.id)),\n` +
    `});\n`;
  write(`${OUT}/routers/${c}.ts`, out);
}

// 5. appRouter.ts — merge the entity routers
{
  let out = `${H}import { router } from '../trpc/init';\n`;
  for (const e of entities) out += `import { ${camel(e.name)}Router } from './routers/${camel(e.name)}';\n`;
  out += `\nexport const appRouter = router({\n`;
  for (const e of entities) out += `  ${e.table}: ${camel(e.name)}Router,\n`;
  out += `});\nexport type AppRouter = typeof appRouter;\n`;
  write(`${OUT}/appRouter.ts`, out);
}

// 6. repos.ts — one storeRepository per entity (the driver seam, v2.0 impl)
{
  let out =
    `${H}import { storeRepository } from '../repo/storeRepository';\n` +
    `import type { ${entities.map((e) => e.name).join(', ')} } from './schema';\n` +
    `import { ${entities.map((e) => camel(e.name) + 'Seed').join(', ')} } from './seed';\n\n` +
    `export const repos = {\n`;
  for (const e of entities) out += `  ${e.table}: storeRepository<${e.name}>('${e.table}', ${camel(e.name)}Seed),\n`;
  out += `};\n`;
  write(`${OUT}/repos.ts`, out);
}

// 7. hooks.ts — typed hooks: reactive reads via useCollection, writes via the tRPC caller
{
  let out =
    `${H}//\n// Reads come from useCollection (the reactive store) so screens re-render across\n// the app; writes go through the in-process tRPC caller, which mutates the SAME\n// store instance — no cache reconciliation.\nimport { useCollection } from '@/lib/store';\n` +
    `import { api } from '../client';\n` +
    `import type { ${entities.map((e) => e.name).join(', ')} } from './schema';\n` +
    `import { ${entities.map((e) => camel(e.name) + 'Seed').join(', ')} } from './seed';\n`;
  for (const e of entities) {
    const hook = 'use' + cap(e.table);
    out += `\nexport function ${hook}() {\n`;
    out += `  const { items, ready } = useCollection<${e.name}>('${e.table}', ${camel(e.name)}Seed);\n`;
    out += `  return {\n`;
    out += `    items,\n    ready,\n`;
    out += `    create: (input: Parameters<typeof api.${e.table}.create>[0]) => api.${e.table}.create(input),\n`;
    out += `    update: (id: string, patch: Parameters<typeof api.${e.table}.update>[0]['patch']) => api.${e.table}.update({ id, patch }),\n`;
    out += `    remove: (id: string) => api.${e.table}.remove({ id }),\n`;
    out += `  };\n}\n`;
  }
  write(`${OUT}/hooks.ts`, out);
}

// 8. index.ts — barrel + manifest (drives mechanical uninstall)
{
  const files = [...manifest, `${OUT}/index.ts`].map((f) => f.replace(`${OUT}/`, './'));
  let out =
    `${H}export * from './hooks';\nexport * from './schema';\nexport type { AppRouter } from './appRouter';\n\n` +
    `/** Every file this generator emits — delete these + revert hook wiring to uninstall v2.0. */\nexport const BACKEND_MANIFEST: string[] = ${JSON.stringify(files, null, 2)};\n`;
  write(`${OUT}/index.ts`, out);
}

console.log(`\ngen-backend: done. ${manifest.length + 1} files under ${OUT}/.`);
